---
title: "Figure 3a Plots and CSVs"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)
library(reticulate)
library("RColorBrewer")

knitr::opts_knit$set(root.dir = '~/repo/ui_rep_rate')
```

```{r load data}
source("../lab_code/prelim.R")

wages <- read_csv("analysis/release/wages_with_replacement_rates.csv")

deciles <- read_rds("analysis/release/deciles.rds")

logit_fit <- read_rds("analysis/release/logit_fit.rds")

wages_logit_weights <- read_csv("analysis/release/wages_logit_weights_filtered.csv")
```

```{r rep rate tables}
wages_logit_weights <- wages %>%
  mutate(inc_decile = cut(weekly_earnings, deciles),
         two_digit_ind = as.factor(two_digit_ind)) %>%
  broom::augment(logit_fit, newdata = .,
                 type.predict = "response") %>%
  mutate(weight = weight * .fitted)

elig_deciles <- wages_logit_weights %>%
  with(Hmisc::wtd.quantile(weekly_earnings,
                           weight,
                           seq(0, 1, length.out = 11)))
elig_deciles[1] <- -Inf
elig_deciles[11] <- Inf

# old code I copied and pasted from /analysis/source/plot_ui.R:
#
# replacement_rate_by_decile <- wages_logit_weights  %>%
#   mutate(eligible_decile = cut(weekly_earnings, elig_deciles)) %>%
#   group_by(eligible_decile) %>%
#   summarise_at(vars(contains("replacement_rate")),
#                ~ Hmisc::wtd.quantile(.x, weights = weight, probs = 0.5)) %>%
#   mutate(replacement_rate_FPUC = replacement_rate_FPUC - replacement_rate,
#          replacement_rate_Jan = replacement_rate) %>%
#   select(-replacement_rate) %>%
#   pivot_longer(cols = contains("replacement"), names_to = "type",
#                values_to = "replacement_rate", names_prefix = "replacement_rate_")

decile_rep_rates_600 <- wages_logit_weights  %>%
  mutate(eligible_decile = cut(weekly_earnings, elig_deciles)) %>%
  group_by(eligible_decile) %>%
  summarise_at(vars(contains("replacement_rate")),
               ~ Hmisc::wtd.quantile(.x, weights = weight, probs = 0.5)) %>%
  rename(replacement_rate_Jan = replacement_rate) %>%
  pivot_longer(cols = contains("replacement"), names_to = "type",
               values_to = "replacement_rate", names_prefix = "replacement_rate_")

write.csv(decile_rep_rates_600, "analysis/release/fig3_rep_rates_600.csv")

decile_rep_rates_300 <- wages_logit_weights %>%
  mutate(replacement_rate_FPUC = (benefits_amount + 300)/weekly_earnings,
         eligible_decile = cut(weekly_earnings, elig_deciles)) %>%
  group_by(eligible_decile) %>%
  summarise_at(vars(contains("replacement_rate")),
               ~ Hmisc::wtd.quantile(.x, weights = weight, probs = 0.5)) %>%
  rename(replacement_rate_Jan = replacement_rate) %>%
  pivot_longer(cols = contains("replacement"), names_to = "type",
               values_to = "replacement_rate", names_prefix = "replacement_rate_")

write.csv(decile_rep_rates_300, "analysis/release/fig3_rep_rates_300.csv")
```

```{r plot}
palette <- RColorBrewer::brewer.pal(6, "Blues")

# old code I copied and pasted from /analysis/source/plot_ui.R
#
# replacement_rate_by_decile %>%
#   filter(type %in% c("FPUC", "Jan")) %>%
#   ggplot(aes(eligible_decile, replacement_rate, fill = type)) +
#   geom_col(position = position_stack()) +
#   geom_hline(yintercept = 1) +
#   scale_x_discrete(labels = label_cuts("dollar")) +
#   scale_y_continuous(labels = scales::percent) +
#   labs(y = "Median replacement rate",
#        x = "Pre-job loss weekly earnings (deciles)") +
#   fte_theme(dark_text = TRUE, legend_title_on = FALSE) +
#   theme(panel.grid.major.x = element_blank(),
#         legend.position = c(0.7, 0.82),
#         axis.text.x = element_text(angle = 30, hjust = .8)) +
#   scale_fill_manual(name = NULL,
#                     #values = c("cornflowerblue","palegoldenrod"),
#                     values = c(palette[5],
#                                colortools::adjacent(palette[5])[3]),
#                     labels = c("Without $600 supplement",
#                                "With $600 supplement"))

decile_rep_rates_600 %>%
   arrange(desc(replacement_rate)) %>%
   ggplot(aes(x = eligible_decile,
              y = replacement_rate,
              fill = type)) +
   geom_col(position = "identity") +
   geom_hline(yintercept = 1) +
   scale_x_discrete(labels = label_cuts("dollar")) +
   scale_y_continuous(labels = scales::percent) +
   labs(y = "Median replacement rate",
        x = "Pre-job loss weekly earnings (deciles)") +
   fte_theme(dark_text = TRUE, legend_title_on = FALSE) +
   theme(panel.grid.major.x = element_blank(),
         legend.position = c(0.7, 0.82),
         axis.text.x = element_text(angle = 30, hjust = .8)) +
   scale_fill_manual(name = NULL,
                     values = c(palette[5],
                       colortools::adjacent(palette[5])[3]),
                     labels = c("Without $600 supplement",
                                "With $600 supplement"))

ggsave("analysis/issue_54_fig3a_csv/quantile_plot_600_FPUC.png", width = 8, height = 4.5)

decile_rep_rates_300 %>%
   arrange(desc(replacement_rate)) %>%
   ggplot(aes(x = eligible_decile,
              y = replacement_rate,
              fill = type)) +
   geom_col(position = "identity") +
   geom_hline(yintercept = 1) +
   scale_x_discrete(labels = label_cuts("dollar")) +
   scale_y_continuous(labels = scales::percent) +
   labs(y = "Median replacement rate",
        x = "Pre-job loss weekly earnings (deciles)") +
   fte_theme(dark_text = TRUE, legend_title_on = FALSE) +
   theme(panel.grid.major.x = element_blank(),
         legend.position = c(0.7, 0.82),
         axis.text.x = element_text(angle = 30, hjust = .8)) +
   scale_fill_manual(name = NULL,
                     values = c(palette[5],
                       colortools::adjacent(palette[5])[3]),
                     labels = c("Without $300 supplement",
                                "With $300 supplement"))

ggsave("analysis/issue_54_fig3a_csv/quantile_plot_300_FPUC.png", width = 8, height = 4.5)
```